# Generated by Django 2.1.4 on 2019-01-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_finished', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'ocr_request',
            },
        ),
        migrations.CreateModel(
            name='OcrResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('ocr_request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr_dispatcher.OcrRequest')),
            ],
            options={
                'db_table': 'ocr_result',
            },
        ),
    ]
