# Generated by Django 2.1.4 on 2019-01-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('type', models.CharField(default='pdf', max_length=20)),
                ('syndic_id', models.IntegerField(blank=True, null=True)),
                ('copro_id', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='OcrRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='WAITING', max_length=30)),
                ('number_files', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'ocr_request',
            },
        ),
        migrations.CreateModel(
            name='OcrResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('status', models.CharField(default='WAITING', max_length=30)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr_dispatcher.Document')),
                ('ocr_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr_dispatcher.OcrRequest')),
            ],
            options={
                'db_table': 'ocr_result',
            },
        ),
    ]
