# Generated by Django 2.1.4 on 2019-01-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrrequest',
            name='timestamp_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
