# Generated by Django 2.1.4 on 2019-01-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_dispatcher', '0002_auto_20190103_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrequest',
            name='status',
            field=models.CharField(default='WAITING', max_length=30),
        ),
    ]
