# Generated by Django 2.1.4 on 2019-01-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_dispatcher', '0003_ocrrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocrresult',
            old_name='ocr_request_id',
            new_name='ocr_request',
        ),
    ]
