# Generated by Django 2.1.4 on 2019-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_dispatcher', '0004_auto_20190104_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='test_file')),
                ('path', models.TextField(default='very/long/path')),
                ('type', models.CharField(default='pdf', max_length=20)),
                ('syndic', models.IntegerField(default=1)),
                ('copro', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
