# Generated by Django 2.1.4 on 2019-01-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_dispatcher', '0005_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='copro',
            new_name='copro_id',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='syndic',
            new_name='syndic_id',
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='copro_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ocr_dispatcher.File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='syndic_id',
            field=models.IntegerField(default=1),
        ),
    ]
