# Generated by Django 2.1.4 on 2019-01-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_dispatcher', '0006_auto_20190104_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrrequest',
            name='number_files',
            field=models.IntegerField(default=1),
        ),
    ]
