# Generated by Django 2.1.4 on 2019-01-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_dispatcher', '0008_ocrresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrresult',
            name='copro_id',
        ),
        migrations.RemoveField(
            model_name='ocrresult',
            name='syndic_id',
        ),
    ]
